FROM node:22 AS builder

WORKDIR /app

COPY "package.json" .

RUN npm install

COPY . .

RUN ./node_modules/.bin/prisma generate

RUN npm run build


#Production
FROM node:22

WORKDIR /app

COPY "package.json" .

RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist

COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma

EXPOSE 3000

CMD [ "node", "./dist/index.js" ]


