### TESTING API
GET http://localhost:3000/

### Testing Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "testUser",
    "password": "testPassword"
}

### Testing Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "hannan",
    "password": "hello123"
}


### TESTING SESSION CREATION
POST  http://localhost:3000/api/session/create
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzcyMDAzNTgzLCJleHAiOjE3NzIwMDcxODN9.3QyWmGN0j6LS0Kp28cavMv_2ttvL7Yvkz8v_XES-oMU
### Testing upload
POST http://localhost:3000/api/session/3/upload
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzcyMTA0NTcxLCJleHAiOjE3NzIxMDgxNzF9.1JNYwWh7S_9uUbrqEjqVYeLzcWw35eAEvN9xxL7G69U
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="pdf"; filename="test.pdf"
Content-Type: application/pdf

< ./src/research_paper.pdf
--boundary--

### TESTING SESSION DELETE
POST http://localhost:3000/api/session/2/delete
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzcxOTg4Mjg3LCJleHAiOjE3NzE5OTE4ODd9.Sz0csHl40QLWKdT56zNbh1gGeL8eSd8mcGBCB7cSq10

### TESTING MESSAGING POINT 
POST http://localhost:3000/api/session/9/message
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzcyMjMxMTQ5LCJleHAiOjE3NzIyMzQ3NDl9.R55BNhvy5k9KsNUBG6HNWogtLR8FoMDsxH7JvsFevbs
Content-Type: application/json

{
    "question": "Explain the abstract"
}
###GET ALL SESSSIONS

GET http://localhost:3000/api/session/getAll
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzcyMTUzNTEyLCJleHAiOjE3NzIxNTcxMTJ9.-Ks_GfJNyT1oGYX6TOvNwuKQaVnf8GbBTU7VkmmcSyw

### GET SINGLE SESSION
GET http://localhost:3000/api/session/get/4
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzcyMTUzNTEyLCJleHAiOjE3NzIxNTcxMTJ9.-Ks_GfJNyT1oGYX6TOvNwuKQaVnf8GbBTU7VkmmcSyw