### TESTING API
GET http://localhost:3000/

### Testing Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "testUser",
    "password": "testPassword"
}

### Testing Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "hannan",
    "password": "hello123"
}


### TESTING SESSION CREATION
POST  http://localhost:3000/api/session/create
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzcxOTY1NzU2LCJleHAiOjE3NzE5NjkzNTZ9.7gYvQkidJjtXxQPalbiowfha65XOqixXhfLeMr2Ai9A

### Testing upload
POST http://localhost:3000/api/session/2/upload
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzcxOTg4Mjg3LCJleHAiOjE3NzE5OTE4ODd9.Sz0csHl40QLWKdT56zNbh1gGeL8eSd8mcGBCB7cSq10
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="pdf"; filename="test.pdf"
Content-Type: application/pdf

< ./src/research_paper.pdf
--boundary--

### TESTING SESSION DELETE
POST http://localhost:3000/api/session/2/delete
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzcxOTg4Mjg3LCJleHAiOjE3NzE5OTE4ODd9.Sz0csHl40QLWKdT56zNbh1gGeL8eSd8mcGBCB7cSq10

### TESTING MESSAGING POINT 
POST http://localhost:3000/api/session/2/message/question
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzcxOTg4Mjg3LCJleHAiOjE3NzE5OTE4ODd9.Sz0csHl40QLWKdT56zNbh1gGeL8eSd8mcGBCB7cSq10
Content-Type: application/json

{
    "user": "Explain the abstract"
}
