### TESTING API
GET http://localhost:3000/

### Testing Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "testUser",
    "password": "testPassword"
}

### Testing Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "testUser",
    "password": "testPassword"
}


### TESTING SESSION CREATION
POST  http://localhost:3000/api/session/create
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzcxNzM0NjU2LCJleHAiOjE3NzE3MzgyNTZ9.dbE-FwNl4tfRQKmn6biWzZrdKVX9U1xA-fPrYtT3dZ0

### Testing upload
POST http://localhost:3000/api/session/1/file/upload
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzcxNzM0NjU2LCJleHAiOjE3NzE3MzgyNTZ9.dbE-FwNl4tfRQKmn6biWzZrdKVX9U1xA-fPrYtT3dZ0
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="pdf"; filename="test.pdf"
Content-Type: application/pdf

< ./src/research_paper.pdf
--boundary--

### TESTING SESSION DELETE
POST http://localhost:3000/api/session/1/delete
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzcxNzM0NjU2LCJleHAiOjE3NzE3MzgyNTZ9.dbE-FwNl4tfRQKmn6biWzZrdKVX9U1xA-fPrYtT3dZ0

### TESTING MESSAGING POINT 
POST http://localhost:3000/api/session/1/message/question
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzcxNzM0NjU2LCJleHAiOjE3NzE3MzgyNTZ9.dbE-FwNl4tfRQKmn6biWzZrdKVX9U1xA-fPrYtT3dZ0
Content-Type: application/json

{
    "user": "Explain the abstract"
}
