name: Run Tests

on:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server    
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
      OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
